### ISSUE TITLE
Considérer les domaines pointant sur le répertoire ./p

### ISSUE THREAD

**Issue by marienfressinaud** [purexo/FreshRSS-Notify#1]
L'extension ne peut pas fonctionner si le (sous-)domaine pour FRSS pointe sur le répertoire `./p`. Exemple : http://demo.freshrss.org/i/

**Comment by purexo** [comment]
J'ai repris le développement de mon Add-on, J'avais complètement oublié ça.

Je vais réfléchir à ajouter une variable dans les préférences pour définir le path de l'API.
Après c'est un cas exceptionnel, et je doute que beaucoup essaient d'utiliser l'api d'une démo avec un arrangement de sous domaines étrange ^^

**Comment by marienfressinaud** [comment]
>  Après c'est un cas exceptionnel, et je doute que beaucoup essaient d'utiliser l'api d'une démo avec un arrangement de sous domaines étrange ^^

Ce n'est justement pas censé être exceptionnel, c'est ce qui est recommandé d'un point de vue sécurité :p En fait tu n'as pas besoin d'ajouter un champ supplémentaire, il suffit que l'utilisateur ajoute le `/p` à l'url tout simplement

**Comment by purexo** [comment]
Bon, je verrai ça un autre jour, mais avec les deux champs ça devrait fonctionner.
Le je viens de passer plusieurs heures sur de la manipulation DOM "safe" pour pas utiliser de innerHTML pour la review

**Comment by marienfressinaud** [comment]
En fait c'est simple : 

1. Tu laisses l'utilisateur saisir l'URL "de base" (exemples : http://exemple.com/FreshRSS/p, http://rss.exemple.com)
2. À partir de cette URL, tu détermines l'URL de l'API en ajoutant `/api/greader.php` (ce qui donnera au final : http://exemple.com/FreshRSS/p/api/greader.php, http://rss.exemple.com/api/greader.php)

Donc par rapport à ton code actuel, tu as juste à garder le champ "URL", tu peux supprimer celui d'accès à l'API et tu peux en faire une constante d'une valeur de `/api/greader.php`.

**Comment by purexo** [comment]
Partant du principe, que les gens peuvent configurer leur serveur http comme ils veulent, (voir n'importe comment). Je pense que je vais rester sur 2 champs :

- url : soit celle d’accès "normal" pour aller lire ses flux.
- APIurl : donc l'adresse de l'api, chemin vers le fichier greader.php

Et les deux champs seraient en url absolu.

Pour ma part, si je devais me configurer des sous domaines pour mon instance de FreshRSS, j'aurais un sous domaine rss. qui pointe vers la partie siteweb de FreshRSS
et un sous domaine api.rss. qui pointe vers le fichier api de FreshRSS

**Comment by purexo** [comment]
![http://screencloud.net/v/35xQ]

Voila : [v2.1.0](https://github.com/purexo/FreshRSS-Notify/releases/tag/2.1.0) prête

URL et APIURL sont maintenant [dissociés](https://www.youtube.com/watch?v=5lUBlW72qBQ)
Il faut donc bien penser à les redéfinir
