### ISSUE TITLE
api url

### ISSUE THREAD

**Issue by azlux** [purexo/FreshRSS-Notify#2]
Bonjour,
J'ai lu les différents messages et push sur les entrées URL de l’addon, mais j'arrive toujours pas à la faire fonctionner.
erreur : "check your id or instance url"
Essayer d'être plus clair dans le README.md pour savoir quel url mettre.
Si j'ai bien compris ce serai : 
https://*****.**/freshrssfoler/p/i pour "URL"  et 
https://*****.**/freshrssfoler/p/api/ pour "API's url".

Cordialement,
Az

**Comment by purexo** [comment]
Bonjour,

https://purexo.eu/FreshRSS/ c'est mon URL
https://purexo.eu/FreshRSS/p/api/ c'est pour l'api

Identifiant de connexion est celui que j'utilise dans le navigateur (interface web)

Je pense que ton problème viens du mot de passe. il faut que tu utilise le mot de passe API.
Il ce configure ici : /FreshRSS/p/i/?c=user&a=profile quand tu es connecté
C'est le deuxième champ de mot de passe.

**Comment by azlux** [comment]
merci pour la réponse,
mais en fait il ne veux toujours pas, donc oui j'ai mis le mdp au bon endroit et l'accès api est autorisé.
Mais je me demande si c'est pas parce que je n'ai que le dossier /p d'accessible depuis l’extérieur  (comme dit dans la doc : sudo ln -s /usr/share/FreshRSS/p /var/www/html/FreshRSS), donc mon url tombe déjà dans le dossier /p/ de Freshrss.
Y aurais-t-il un lien ?

**Comment by purexo** [comment]
c'est possible en effet. Mais je sais pas. 
Le plus important est que `/FreshRSS/p/api/` soit accessible de l'exterieur.

Par contre, j'étais pas au courant de cette pratique, en fournissant à l'addon l'adresse 'root' de FreshRSS, il rajoute lui même le /p/i lorsqu'on clic pour accéder à la version web pour lire ses flux.

Mais pour l'api normalement c'est bon, donc j'ai du mal à comprendre ce qui ce passe chez toi

**Comment by purexo** [comment]
Vu que tu as fait un simlink `.../FreshRSS/p/` -> `.../FreshRSS/`
Je pense que l'url de ton api doit être

`.../FreshRSS/api/` au lieu de `/FreshRSS/p/api`

**Comment by azlux** [comment]
Je comprend pas trop, le pire c'est que l'app essai d’accéder à freshrss.
Dans nginx j'ai le log : https://*****.fr/rss/api//greader.php/accounts/ClientLogin?Email=*****&Passwd=***** en 200 (en tapant l'adresse j'ai bien un SID et Auth)

**Comment by purexo** [comment]
C'est vraiment étrange. Tu es le premier à me remonter ce soucis. De mon côté ça marche bien.

Si les URL sont bonne je vois pas ce qui peux gener.

Tu as bien enlevé le `/p` de l'url API comme montré plus haut ?

**Comment by purexo** [comment]
URL : `https://****.fr/rss/` (fonctionnera probablement pas mais c'est pas grave)
API : `https://***.fr/rss/api/`

Essaye comme ça.

**Comment by azlux** [comment]
oui, c'est déjà comme ça. hoooo ca marche (dites merci au cache vachement persistant de firefox).

**Comment by purexo** [comment]
xD En effet. Je me disais bien. Sinon je vois vraiment pas ce que ça aurait pu être

**Comment by purexo** [comment]
Du coup, Problème Résolu.

Résumé : faire pointer l'API URL vers le dossier `api` de freshrss ce trouvant dans `/FreshRSS/p/api` normalement.

**Comment by azlux** [comment]
donc conclusion : 
- Firefox avait en cache l'erreur 500 donc les changement n'avait aucun effet.
- Ils ont mit en recommandation de ne mettre que le dossier /p en public car les autres contiennent des info sensibles.
- Pour ceux que ça intéresse il y a en plus de la doc l'extension php_gmp à activer (php7 ne l'avait pas par défaut, surement ma conf)
- Si le readme pouvait être un peu plus clair stp pour les url (les anglophone ne comprendrons pas forcement cet issue)

**Comment by purexo** [comment]
Je vais voir ça
