### ISSUE TITLE
Mozzila signed addons

### ISSUE THREAD

**Issue by azlux** [purexo/FreshRSS-Notify#3]
Since the new version, the addons need to be [mozzilla signed](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox) to be installed. We cannot force the install any more.

I've install the developer version of firefox to continue to have this possibility.

**Comment by purexo** [comment]
yeah, sorry for the inconvenience, You should use plugin from addon repository => https://addons.mozilla.org/fr/firefox/addon/freshrss-notify/ (they're same version ;-))

a day, i'll made a makefile for generate two version :

1. with full signed revision for Firefox addon repository
2. fast signed for github release

**Comment by azlux** [comment]
Thank ! The one from the mozilla website is enough !
