### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by azlux** [Purexo/FreshRSS-Notify#5]
Je viens juste de voir que cette extension me désactive le mutli-process de firefox.
Serais-il possible de regarder ça ?

Merciii

**Comment by Purexo** [comment]
C'est normal, je n'ai pas encore eu le temps de recoder l'extension avec web-extension (même si c'est en cours sur la branche https://github.com/Purexo/FreshRSS-Notify/tree/web-extension, mais loin d'être fini)

Donc deux possibilités :

1. garder l'extension mais ne pas avoir le multi-process
2. désactiver l'extension et bénéficier du multi-process

J'espère avoir fini d'ici fin septembre en tout cas.

Désolé pour le dérangement.

**Comment by azlux** [comment]
Pas un soucis pour moi.
Je vais scripter mon raspb quand il auras des nouvelles notif RSS en attendant.

Merci pour ton boulot !

**Comment by azlux** [comment]
si t'as besoin de testeur, je peux (j'ai juste pas la procédure pour créer les xpi depuis les sources)

**Comment by azlux** [comment]
Je suis tombé sur ce projet : https://framagit.org/dohseven/freshrss-watcher
Peut-être voir avec eux pour ne pas avoir 2 projets différents ?

**Comment by Purexo** [comment]
Bonjour,

J'imagine que ça ce vois que j'ai pas du tout respecter les délais que je m'étais fixé.
pour tout dire, j'ai abandonné mon extension (et je me contente d'un onglet épinglé) par manque de temps et surtout je n'ai pas réussi à adapter mon extension vers ce nouveau format / architecture.

Ca viens probablement de mon manque de compréhension, mais j'ai rencontre beaucoup de soucis et je n'arrive pas à faire communiquer mon background process avec mon panel.

Si un jours je veux m'y remettre je me pencherai sur ce repo pour ajouter des fonctionnalité (comme avoir de une liste des derniers flux dans un panel ^^) mais c'est pas pour tout de suite.

**Comment by Purexo** [comment]
Salut, je me suis sortis les doigts du cul cette semaine, et comme ça sans crier gare j'ai release une v3 en webextension ;-)

Les mêmes fonctionnalité sont présente, plus possibilité de disable les notif de non-lus

**Comment by Purexo** [comment]
Pour le moment c'est juste dans les release github, je me pencherai sur l'addon store de FF plus tard.

Du coup je close l'issue ;-)
