### ISSUE TITLE
Freeze Firefox for 30s

### ISSUE THREAD

**Issue by azlux** [Purexo/FreshRSS-Notify#6]
Hi,
Now you have release the web-extension, I using it.
I see sometime, clicking on the freshrss ison can freeze the app for 30s.
My CPU go high.

Is there are any log I can give you ?

Az

**Comment by Purexo** [comment]
Hi, sorry about that, I don't encounter this issue.

maybe I paralyse to many things when I render RSS items on panel and DOM cannot handle it on small processor.

how many feed do you display (5 by default in option panel), and your feed have a bunch of things in it or is it small ?
and what is your processor ?

**Comment by azlux** [comment]
It's appear on my home computer and work computer.
Both are under Windows 10. Refresh every 15min, display 2 feed.
I have a Intel i7-3632QM
My freshrss have around 20 news every days.

**Comment by azlux** [comment]
Hi @Purexo 
I've enable the addons debug on firefox.
I see some error:
```
Error: "Could not establish connection. Receiving end does not exist."
	<anonymous> moz-extension://1c135b65-5f34-4bae-83a5-f998c8eaa412/src/back/main.js:78:7
```
a lot of time when I start the debug.

and

```
Public-Key-Pins : le site a spécifié un en-tête qui n’a pas pu être analysé correctement.
```
(Not sure it's really an error)

But the main problem is the network part:
![image](https://user-images.githubusercontent.com/11210117/51600601-a333fe00-1f02-11e9-95a9-68841f555426.png)
11.9 Mo when there are unread feed ?
That a lot.
The debugger say : SyntaxError: JSON.parse: unterminated string at line 1 column 1048577 of the JSON data

I will send you the json by email.

Azlux

**Comment by Purexo** [comment]
How, i've forgot I'de a similar bug and fix it here : https://github.com/Purexo/FreshRSS-Notify/blame/master/src/back/lib/RssApi.class.js#L199

In case you ask for 0 unreads, don't know why but server respond with a big response in incorrect format :/

You just have to update your version :

- https://addons.mozilla.org/fr/firefox/addon/freshrss-notify-webextension/
- https://github.com/Purexo/FreshRSS-Notify/releases/latest

Please prefer firefox addon-store for auto-update ;-)

**Comment by azlux** [comment]
I have the version 3.0.3 and it didn't change anything.
May the API have an issue ?

**Comment by Purexo** [comment]
https://github.com/Purexo/FreshRSS-Notify/blob/c527ed8d6746d90a248dee0eb5da4987004d2d37/src/back/lib/RssApi.class.js#L187

I release a new version, addon-store + github release.
The problem should be solved now ^^

**Comment by azlux** [comment]
It's working well.
Thanks a lot !
